#ifndef PINS_H
#define PINS_H

/* -----------------------------------------------------------
 * UART HANDLE
 * ----------------------------------------------------------- */
/* Set this to the HAL UART handle used in CubeMX (huart1, huart2, etc.) */
#define UART_HANDLE    huart2     // change to huart1, huart3 etc. if needed

/* -----------------------------------------------------------
 * LED CONTROL PIN
 * ----------------------------------------------------------- */
/* Example: Nucleo F303K8 used PB3
   For STM32F407VET6 Discovery you might change to GPIOD/PD12 */
#define LED_PORT       GPIOB
#define LED_PIN        GPIO_PIN_3

/* -----------------------------------------------------------
 * (Optional) Stepper MOTOR PINS
 * ----------------------------------------------------------- */
/* If you later enable stepper control, change these to match CubeMX */
#define STEP_PORT      GPIOA
#define STEP_PIN       GPIO_PIN_5

#define DIR_PORT       GPIOA
#define DIR_PIN        GPIO_PIN_6

#define EN_PORT        GPIOA
#define EN_PIN         GPIO_PIN_7

/* -----------------------------------------------------------
 * Timer used for stepper (optional)
 * ----------------------------------------------------------- */
/* Use the TIM handle name generated by CubeMX (htim2, htim3, ...) */
#define STEPPER_TIMER  htim2

#endif /* PINS_H */
